CREATE OR REPLACE FILE FORMAT EUROPEAN_SOCCER_DB.RAW.CSV_FILE_FORMAT
    TYPE = CSV
    PARSE_HEADER = TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', 'NULL', 'null', 'None')
    DATE_FORMAT = AUTO
    TIMESTAMP_FORMAT = AUTO
    ENCODING = 'UTF8';
