USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE STORAGE INTEGRATION s3_integration
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN =
        'arn:aws:iam::055259485374:role/SnowflakeS3ReadPolicy'
    STORAGE_ALLOWED_LOCATIONS = (
        's3://amzn-s3-esd-rafael/raw/'
    );

DESC STORAGE INTEGRATION s3_integration;

CREATE DATABASE IF NOT EXISTS EUROPEAN_SOCCER_DB;
CREATE SCHEMA IF NOT EXISTS EUROPEAN_SOCCER_DB.RAW;
CREATE SCHEMA IF NOT EXISTS EUROPEAN_SOCCER_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS EUROPEAN_SOCCER_DB.MARTS;
CREATE SCHEMA IF NOT EXISTS EUROPEAN_SOCCER_DB.UTILS;

USE EUROPEAN_SOCCER_DB.UTILS;
CREATE OR REPLACE STAGE s3_raw_stage
URL = 's3://amzn-s3-esd-rafael/raw/'
STORAGE_INTEGRATION = s3_integration;

LIST @s3_raw_stage;


USE DATABASE EUROPEAN_SOCCER_DB;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT csv_format
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', 'null', '');

USE DATABASE EUROPEAN_SOCCER_DB;
USE SCHEMA UTILS;

SELECT
    $1 AS country_id,
    $2 AS country_name
FROM @s3_raw_stage/Country.csv
(
    FILE_FORMAT => 'EUROPEAN_SOCCER_DB.RAW.CSV_FORMAT'
)
LIMIT 10;