
SELECT 'COUNTRY' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM COUNTRY
UNION ALL
SELECT 'LEAGUE', COUNT(*) FROM LEAGUE
UNION ALL
SELECT 'PLAYER', COUNT(*) FROM PLAYER
UNION ALL
SELECT 'PLAYER_ATTRIBUTES', COUNT(*) FROM PLAYER_ATTRIBUTES
UNION ALL
SELECT 'TEAM', COUNT(*) FROM TEAM
UNION ALL
SELECT 'TEAM_ATTRIBUTES', COUNT(*) FROM TEAM_ATTRIBUTES
UNION ALL
SELECT 'MATCH', COUNT(*) FROM MATCH
ORDER BY TABLE_NAME;
