
CALL UTILS.COUNT_DUPLICATE(
    'EUROPEAN_SOCCER_DB.RAW.COUNTRY',
    'ID'
);

CALL UTILS.COUNT_DUPLICATE(
    'EUROPEAN_SOCCER_DB.RAW.LEAGUE',
    'ID'
);

CALL UTILS.COUNT_DUPLICATE(
    'EUROPEAN_SOCCER_DB.RAW.MATCH',
    'ID'
);

CALL UTILS.COUNT_DUPLICATE(
    'EUROPEAN_SOCCER_DB.RAW.PLAYER_ATTRIBUTES',
    'ID'
);

CALL UTILS.COUNT_DUPLICATE(
    'EUROPEAN_SOCCER_DB.RAW.PLAYER',
    'ID'
);

CALL UTILS.COUNT_DUPLICATE(
    'EUROPEAN_SOCCER_DB.RAW.TEAM_ATTRIBUTES',
    'ID'
);

CALL UTILS.COUNT_DUPLICATE(
    'EUROPEAN_SOCCER_DB.RAW.TEAM',
    'ID'
);