with source as(
    select *
    from {{ source('raw', 'match') }}
),

renamed as(
    select
        id::integer as match_id,
        country_id::integer as country_id,
        league_id::integer as league_id,
        nullif(trim(season), '') as match_season,
        stage::integer as match_stage,
        date as match_date,
        MATCH_API_ID,
        HOME_TEAM_API_ID,
        AWAY_TEAM_API_ID,
        HOME_TEAM_GOAL::integer as HOME_TEAM_GOAL,
        AWAY_TEAM_GOAL::integer as AWAY_TEAM_GOAL,
        HOME_PLAYER_X1,
        HOME_PLAYER_X2,
        HOME_PLAYER_X3,
        HOME_PLAYER_X4,
        HOME_PLAYER_X5,
        HOME_PLAYER_X6,
        HOME_PLAYER_X7,
        HOME_PLAYER_X8,
        HOME_PLAYER_X9,
        HOME_PLAYER_X10,
        HOME_PLAYER_X11,
        AWAY_PLAYER_X1,
        AWAY_PLAYER_X2,
        AWAY_PLAYER_X3,
        AWAY_PLAYER_X4,
        AWAY_PLAYER_X5,
        AWAY_PLAYER_X6,
        AWAY_PLAYER_X7,
        AWAY_PLAYER_X8,
        AWAY_PLAYER_X9,
        AWAY_PLAYER_X10,
        AWAY_PLAYER_X11,
        HOME_PLAYER_Y1,
        HOME_PLAYER_Y2,
        HOME_PLAYER_Y3,
        HOME_PLAYER_Y4,
        HOME_PLAYER_Y5,
        HOME_PLAYER_Y6,
        HOME_PLAYER_Y7,
        HOME_PLAYER_Y8,
        HOME_PLAYER_Y9,
        HOME_PLAYER_Y10,
        HOME_PLAYER_Y11,
        AWAY_PLAYER_Y1,
        AWAY_PLAYER_Y2,
        AWAY_PLAYER_Y3,
        AWAY_PLAYER_Y4,
        AWAY_PLAYER_Y5,
        AWAY_PLAYER_Y6,
        AWAY_PLAYER_Y7,
        AWAY_PLAYER_Y8,
        AWAY_PLAYER_Y9,
        AWAY_PLAYER_Y10,
        AWAY_PLAYER_Y11,
        HOME_PLAYER_1::integer as HOME_PLAYER_1,
        HOME_PLAYER_2::integer as HOME_PLAYER_2,
        HOME_PLAYER_3::integer as HOME_PLAYER_3,
        HOME_PLAYER_4::integer as HOME_PLAYER_4,
        HOME_PLAYER_5::integer as HOME_PLAYER_5,
        HOME_PLAYER_6::integer as HOME_PLAYER_6,
        HOME_PLAYER_7::integer as HOME_PLAYER_7,
        HOME_PLAYER_8::integer as HOME_PLAYER_8,
        HOME_PLAYER_9::integer as HOME_PLAYER_9,
        HOME_PLAYER_10::integer as HOME_PLAYER_10,
        HOME_PLAYER_11::integer as HOME_PLAYER_11,
        AWAY_PLAYER_1::integer as AWAY_PLAYER_1,
        AWAY_PLAYER_2::integer as AWAY_PLAYER_2,
        AWAY_PLAYER_3::integer as AWAY_PLAYER_3,
        AWAY_PLAYER_4::integer as AWAY_PLAYER_4,
        AWAY_PLAYER_5::integer as AWAY_PLAYER_5,
        AWAY_PLAYER_6::integer as AWAY_PLAYER_6,
        AWAY_PLAYER_7::integer as AWAY_PLAYER_7,
        AWAY_PLAYER_8::integer as AWAY_PLAYER_8,
        AWAY_PLAYER_9::integer as AWAY_PLAYER_9,
        AWAY_PLAYER_10::integer as AWAY_PLAYER_10,
        AWAY_PLAYER_11::integer as AWAY_PLAYER_11,
        GOAL,
        SHOTON,
        SHOTOFF,
        FOULCOMMIT,
        CARD,
        CROSS,
        CORNER,
        POSSESSION,
        B365H,
        B365D,
        B365A,
        BWH,
        BWD,
        BWA,
        IWH,
        IWD,
        IWA,
        LBH,
        LBD,
        LBA,
        PSH,
        PSD,
        PSA,
        WHH,
        WHD,
        WHA,
        SJH,
        SJD,
        SJA,
        VCH,
        VCD,
        VCA,
        GBH,
        GBD,
        GBA,
        BSH,
        BSD,
        BSA,
        current_timestamp() as loaded_at
    from source 
)

select *
from renamed

