USE DATABASE EUROPEAN_SOCCER_DB;
USE SCHEMA UTILS;

COPY INTO EUROPEAN_SOCCER_DB.RAW.COUNTRY
FROM @EUROPEAN_SOCCER_DB.UTILS.s3_raw_stage/Country.csv
FILE_FORMAT = (
    FORMAT_NAME = 'EUROPEAN_SOCCER_DB.RAW.CSV_FILE_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

-- COUNTRY

COPY INTO EUROPEAN_SOCCER_DB.RAW.LEAGUE
FROM @EUROPEAN_SOCCER_DB.UTILS.s3_raw_stage/League.csv
FILE_FORMAT = (
    FORMAT_NAME = 'EUROPEAN_SOCCER_DB.RAW.CSV_FILE_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

-- LEAGUE

COPY INTO EUROPEAN_SOCCER_DB.RAW.MATCH
FROM @EUROPEAN_SOCCER_DB.UTILS.s3_raw_stage/Match.csv
FILE_FORMAT = (
    FORMAT_NAME = 'EUROPEAN_SOCCER_DB.RAW.CSV_FILE_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

-- MATCH

COPY INTO EUROPEAN_SOCCER_DB.RAW.PLAYER
FROM @EUROPEAN_SOCCER_DB.UTILS.s3_raw_stage/Player.csv
FILE_FORMAT = (
    FORMAT_NAME = 'EUROPEAN_SOCCER_DB.RAW.CSV_FILE_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

-- PLAYER 

COPY INTO EUROPEAN_SOCCER_DB.RAW.PLAYER_ATTRIBUTES
FROM @EUROPEAN_SOCCER_DB.UTILS.s3_raw_stage/Player_Attributes.csv
FILE_FORMAT = (
    FORMAT_NAME = 'EUROPEAN_SOCCER_DB.RAW.CSV_FILE_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

-- PLAYER ATTRIBUTES

COPY INTO EUROPEAN_SOCCER_DB.RAW.TEAM
FROM @EUROPEAN_SOCCER_DB.UTILS.s3_raw_stage/Team.csv
FILE_FORMAT = (
    FORMAT_NAME = 'EUROPEAN_SOCCER_DB.RAW.CSV_FILE_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

-- TEAM

COPY INTO EUROPEAN_SOCCER_DB.RAW.TEAM_ATTRIBUTES
FROM @EUROPEAN_SOCCER_DB.UTILS.s3_raw_stage/Team_Attributes.csv
FILE_FORMAT = (
    FORMAT_NAME = 'EUROPEAN_SOCCER_DB.RAW.CSV_FILE_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

-- TEAM ATTRIBUTES