TRUNCATE TABLE EUROPEAN_SOCCER_DB.RAW.COUNTRY;

COPY INTO EUROPEAN_SOCCER_DB.RAW.COUNTRY
FROM @EUROPEAN_SOCCER_DB.UTILS.S3_STAGE/Country.csv
FILE_FORMAT = (
    FORMAT_NAME = 'EUROPEAN_SOCCER_DB.RAW.CSV_FILE_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE EUROPEAN_SOCCER_DB.RAW.LEAGUE;

COPY INTO EUROPEAN_SOCCER_DB.RAW.LEAGUE
FROM @EUROPEAN_SOCCER_DB.UTILS.S3_STAGE/League.csv
FILE_FORMAT = (
    FORMAT_NAME = 'EUROPEAN_SOCCER_DB.RAW.CSV_FILE_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE EUROPEAN_SOCCER_DB.RAW.MATCH;

COPY INTO EUROPEAN_SOCCER_DB.RAW.MATCH
FROM @EUROPEAN_SOCCER_DB.UTILS.S3_STAGE/Match.csv
FILE_FORMAT = (
    FORMAT_NAME = 'EUROPEAN_SOCCER_DB.RAW.CSV_FILE_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE EUROPEAN_SOCCER_DB.RAW.PLAYER;

COPY INTO EUROPEAN_SOCCER_DB.RAW.PLAYER
FROM @EUROPEAN_SOCCER_DB.UTILS.S3_STAGE/Player.csv
FILE_FORMAT = (
    FORMAT_NAME = 'EUROPEAN_SOCCER_DB.RAW.CSV_FILE_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE EUROPEAN_SOCCER_DB.RAW.PLAYER_ATTRIBUTES;

COPY INTO EUROPEAN_SOCCER_DB.RAW.PLAYER_ATTRIBUTES
FROM @EUROPEAN_SOCCER_DB.UTILS.S3_STAGE/Player_Attributes.csv
FILE_FORMAT = (
    FORMAT_NAME = 'EUROPEAN_SOCCER_DB.RAW.CSV_FILE_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE EUROPEAN_SOCCER_DB.RAW.TEAM;

COPY INTO EUROPEAN_SOCCER_DB.RAW.TEAM
FROM @EUROPEAN_SOCCER_DB.UTILS.S3_STAGE/Team.csv
FILE_FORMAT = (
    FORMAT_NAME = 'EUROPEAN_SOCCER_DB.RAW.CSV_FILE_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE EUROPEAN_SOCCER_DB.RAW.TEAM_ATTRIBUTES;

COPY INTO EUROPEAN_SOCCER_DB.RAW.TEAM_ATTRIBUTES
FROM @EUROPEAN_SOCCER_DB.UTILS.S3_STAGE/Team_Attributes.csv
FILE_FORMAT = (
    FORMAT_NAME = 'EUROPEAN_SOCCER_DB.RAW.CSV_FILE_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;